[versions]
agp = "8.10.1"
kotlin = "1.9.0"
core = "1.16.0"
gamesActivity = "4.0.0"

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-games-activity = { group = "androidx.games", name = "games-activity", version.ref = "gamesActivity" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

